
services:
  orderdb:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderservice
    ports:
      - "5433:5432"
    volumes:
      - orderdb_data:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"     # AMQP protocol port — your app connects here
      - "15672:15672"   # Management UI — browser
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  paymentdb:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentservice
    ports:
      - "5434:5432"          # different host port — 5432 and 5433 are already taken
    volumes:
      - paymentdb_data:/var/lib/postgresql/data
  
  inventorydb:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventoryservice
    ports:
      - "5435:5432"          # different host port — 5432 and 5433 are already taken
    volumes:
      - inventorydb_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.57 
    ports:
     - "16686:16686"   # Web UI
     - "4317:4317"     # OTLP gRPC receiver — this is what your services will send spans to


volumes:
  orderdb_data:
  paymentdb_data:
  inventorydb_data: